import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Grid } from '@material-ui/core';
import PrimaryButton from '../components/PrimaryButton';
import NegativeButton from '../components/NegativeButton'
import useSWR, {mutate} from 'swr';
import Header from '../components/Header';
import {useState} from 'react';
import Divider from '@material-ui/core/Divider';
import Loading from '../components/Loading';


type Props = {
  anime: string,
  character: string,
  quote: string,
}

const Home: NextPage = () => {

  const [loadingState, setLoadingState] = useState<boolean>(false);

  async function fetcher(url: string): Promise<Props | null> {
    const response = await fetch(url);
    setLoadingState(false);
    return response.json();
  }
  const { data, error } = useSWR('https://animechan.vercel.app/api/random', fetcher);

  const [charaData, setCharaData] = useState<Props[]>([]);

  if(error){
    <p>リロードしてください</p>
  }

  if(!data || loadingState){
    return (
      <Loading loadingText={'データを取得中'} />
    )
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className={styles.body} >
          <Grid container justifyContent='center' spacing={3}>
                <Grid item xs={12} sm={8}>
                    <h1>AnimeChan</h1>
                    <p>Anime：{data.anime}</p>
                    <p>Character：{data.character}</p>
                    <p>Quote：{data.quote}</p>
                    <PrimaryButton fullWidth={true} label={'Add anime'}
                      onClick={() => {
                        setLoadingState(true)
                        setCharaData([...charaData, data]);
                        mutate('https://animechan.vercel.app/api/random');
                    }} />
                </Grid>
                <Grid item xs={12} sm={4}>
                  <div className={styles.little_Space} />
                  {
                      charaData.map((data, index) => (
                        <div key={index}>
                          <p>Anime：{data.anime}</p>
                          <p>Character：{data.character}</p>
                          <p>Quote：{data.quote}</p>
                          <Divider />
                        </div>
                      ))
                  }
                  <NegativeButton fullWidth={true} label={'Reset'}
                    onClick={() => {
                      setCharaData([]);
                  }} />
                </Grid>
            </Grid>
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Watch Code
        </a>
      </footer>
    </div>
  )
}

export default Home
